apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'

group = 'expo.modules.smsreader'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "expo.modules.smsreader"
  defaultConfig {
    minSdkVersion 24
  }
  compileSdk 36
  lint {
    abortOnError false
  }
}

dependencies {
  implementation "androidx.core:core-ktx:1.13.1"
}
